"""Add packages.sourceOfferId — links an auto-generated Package back to the
accepted Offer it was created from

Revision ID: 20260710_02
Revises: 20260710_01
Create Date: 2026-07-10

Why this migration exists:
  - PRD 3 (custom plan & booking workflow): when a traveler accepts an
    agency's offer on a Plan, a Package is now created at the agreed price
    (see app/services/offers.py::accept_offer). This column traces that
    Package back to the Offer/Plan it came from, distinguishing
    agency-authored catalog packages (sourceOfferId IS NULL) from ones
    generated by an accepted negotiation.

Tables and column names use the camelCase identifiers this repo's other
Prisma-derived tables use, for consistency.
"""

from alembic import op

revision = "20260710_02"
down_revision = "20260710_01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        'ALTER TABLE packages ADD COLUMN IF NOT EXISTS "sourceOfferId" VARCHAR(36) REFERENCES offers(id)'
    )
    op.execute(
        'CREATE INDEX IF NOT EXISTS ix_packages_source_offer_id ON packages ("sourceOfferId")'
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_packages_source_offer_id")
    op.execute('ALTER TABLE packages DROP COLUMN IF EXISTS "sourceOfferId"')
